name: Bug Report
description: Report a confirmed issue
title: "[Bug]: "
labels: ["bug"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "Select how urgent or impactful this issue is."
      options:
        - P0 – Mission Critical (Drop everything for this)
        - P1 – High Priority (Next up, push fast)
        - P2 – Normal Cadence (Keep it on track)
        - P3 – No Urgency (Get to it when possible)
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug
      placeholder: "Describe what’s happening and what’s broken."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: "Summarize what was expected, any impact, environment details, logs, or other clues that help reproduce and fix the issue."
      placeholder: |
        Example:
        - Expected payment to process and show confirmation  
        - Occurs on macOS 15.0 / Chrome 120  
        - Error in console: 'POST /checkout 500'
    validations:
      required: false
