name: Feature Request
description: Suggest a new capability or improvement
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "Select how urgent or impactful this request is."
      options:
        - P0 – Mission Critical (Drop everything for this)
        - P1 – High Priority (Next up, push fast)
        - P2 – Normal Cadence (Keep it on track)
        - P3 – No Urgency (Get to it when possible)
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature
      placeholder: "Describe the capability or improvement being requested."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: "Summarize why this feature matters, what it enables, and any relevant details or dependencies."
      placeholder: |
        Example:
        - Improves workflow efficiency for end users  
        - Addresses frequent support requests  
        - Requires coordination with the API or design team
    validations:
      required: false
